name: on pull_request_target Send Slack Notifications

on:
  workflow_run:
    workflows: ["Dart Pull Request Tests"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        if: contains(github.event.pull_request.labels.*.name, 'test-succeded')
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "pr_name": "${{ github.event.pull_request.title }}",
              "pr_link": "${{ github.event.pull_request.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}