name: Dart Pull Request Tests add label and comment

on:
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
   run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
    - name: Run complete action
      id: complete_action
      run: |
        dart pub get
        cd linteo_extractor
        dart pub get
        dart test
    - name: Add success label
      if: success()
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const prNumber = context.payload.pull_request.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const label = "test-succeded";  // Change to your desired label
          github.issues.removeLabel({
            owner: owner,
            repo: repo,
            issue_number: prNumber,
            name: "test-failed"
            });
          github.issues.addLabels({
            owner: owner,
            repo: repo,
            issue_number: prNumber,
            labels: [label]
            });

          const body = 'Thank you for your pull request!'; // Your comment here
  


          github.issues.createComment({
            owner: owner,
            repo: repo,
            issue_number: prNumber,
            body: body
          });

    - name: Add failure label if tests fail
      if: failure()
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const prNumber = context.payload.pull_request.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const label = "test-failed";  // Change to your desired label
          
          github.issues.removeLabel({
            owner: owner,
            repo: repo,
            issue_number: prNumber,
            name: "test-succeded"
            });

          github.issues.addLabels({
            owner: owner,
            repo: repo,
            issue_number: prNumber,
            labels: [label]
            });

          const body = 'Thank you for your pull request!'; // Your comment here
       
          github.issues.createComment({
            owner: owner,
            repo: repo,
            issue_number: prNumber,
            body: body
          });
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": "Danny Torrence left a 1 star review for your property.",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Danny Torrence left the following review for your property:"
                }
              },
              {
                "type": "section",
                "block_id": "section567",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://example.com|Overlook Hotel> \\n :star: \\n Doors had too many axe holes, guest in room 237 was far too rowdy, whole place felt stuck in the 1920s."
                },
                "accessory": {
                  "type": "image",
                  "image_url": "https://is5-ssl.mzstatic.com/image/thumb/Purple3/v4/d3/72/5c/d3725c8f-c642-5d69-1904-aa36e4297885/source/256x256bb.jpg",
                  "alt_text": "Haunted hotel image"
                }
              },
              {
                "type": "section",
                "block_id": "section789",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Average Rating*\\n1.0"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}