name: Dart Pull Request Tests

on:
    workflow_run:
      workflows: ["On Lints Changed"]
      types:
        - completed

jobs:
   run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
    - name: Run complete action
      id: complete_action
      run: |
        dart pub get
        cd linteo_extractor
        dart pub get