name: Run Tests and Notify on main

on:
  push:
    branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
      - name: Run Tests
        id: test
        run: |
            cd linteo_extractor
            dart pub get
            dart test
  notify-slack:
    needs: test
    runs-on: ubuntu-latest

    steps:
      # - name: Send notification to Slack
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_CHANNEL: hybrid-opensource-github-test
      #     SLACK_COLOR: '#FF5500'  # Customize the message color
      #     SLACK_TITLE: 'Pull Request Notification'
      #     SLACK_ICON: https://github.com/rtCamp.png?size=48
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}  # Your Slack webhook URL
      # - name: Send custom JSON data to Slack workflow
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.24.0
      #   with:
      #     # For posting a rich message using Block Kit
      #     payload: |
      #       {
      #         "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
      #         "blocks": [
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      #             }
      #           }
      #         ]
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      - name: Post to a Slack channel
        id: slack2
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C06F4DH84EP'
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "SLACKBOT: GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}